export const SHOP_ROUTE = "/gigi-janssen-store"
export const LOGIN_ROUTE = "/login"
export const ADMIN_ROUTE = "/admin"
export const PROFILE_ROUTE = "/profile"
export const ORDER_ROUTE = "/order"
export const SEARCH_ROUTE = "/search"
export const LOGOUT_ROUTE = "/logout"
